# Generated by Django 6.0.2 on 2026-02-28 09:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_code', models.CharField(max_length=16, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='elections.election')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ballot', to='tokens.token')),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='BallotChoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abstained', models.BooleanField(default=False)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='ballots.ballot')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='elections.candidate')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='elections.post')),
            ],
            options={
                'ordering': ('post__sort_order', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(fields=('token',), name='uniq_ballot_per_token'),
        ),
        migrations.AddConstraint(
            model_name='ballotchoice',
            constraint=models.UniqueConstraint(fields=('ballot', 'post', 'candidate'), name='uniq_ballot_post_candidate'),
        ),
    ]
