# Generated by Django 6.0.2 on 2026-02-28 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('primary_color_override', models.CharField(blank=True, max_length=16)),
                ('logo_url', models.URLField(blank=True)),
                ('default_public_results_enabled', models.BooleanField(default=False)),
                ('default_results_visibility', models.CharField(choices=[('HIDDEN_UNTIL_CLOSED', 'Hidden until closed'), ('LIVE_ALLOWED', 'Live allowed')], default='HIDDEN_UNTIL_CLOSED', max_length=32)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
