# Generated by Django 6.0.2 on 2026-02-28 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="voter_auto_logout_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Voter auto logout timeout in seconds.",
                validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(3600)],
            ),
        ),
    ]
