# Generated by Django 6.0.1 on 2026-02-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenbatch',
            name='encrypted_tokens_blob',
            field=models.TextField(blank=True, default=''),
        ),
    ]
