# Generated by Django 6.0.2 on 2026-02-28 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="voter_auto_logout_seconds",
            field=models.PositiveIntegerField(
                default=60,
                validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(86400)],
            ),
        ),
    ]
